name: Build

on:
  pull_request:
  release:
    types: [ released ]

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                python: [ '3.12' ]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v6
              with:
                python-version: ${{ matrix.python }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pyinstaller

            - name: Build with PyInstaller (Linux)
              if: matrix.os == 'ubuntu-latest'
              run: |
                chmod +x ./build_linux.sh
                ./build_linux.sh

            - name: Build with PyInstaller (Windows)
              if: matrix.os == 'windows-latest'
              run: |
                ./build_windows.bat

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: TranslateHub-${{ matrix.os }}
                path: dist
